include:
  - path: ../Monitoring/docker-compose.yml

services:
  api-gateway:
    build: .
    image: api-gateway
    environment:
      JWT_SECRET: ${JWT_SECRET}
      EXTERNAL_USER_SERVICE_URL: ${EXTERNAL_USER_SERVICE_URL}
      EXTERNAL_AUTH_SERVICE_URL: ${EXTERNAL_AUTH_SERVICE_URL}
    ports:
      - "8083:8080"
    depends_on:
      - auth-service
      - user-service
      - order-service

  postgres-user-service:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ${POSTGRES_DB_USER_SERVICE}
      POSTGRES_USER: ${POSTGRES_USER_USER_SERVICE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_USER_SERVICE}
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER_USER_SERVICE} -d ${POSTGRES_DB_USER_SERVICE}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}", "--bind", "0.0.0.0" ]

  user-service:
    build: ../UserService
    image: user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: ${DB_URL_USER_SERVICE}
      DB_USERNAME: ${DB_USERNAME_USER_SERVICE}
      DB_PASSWORD: ${DB_PASSWORD_USER_SERVICE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres-user-service
      - redis

  postgres-auth-service:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ${POSTGRES_DB_AUTH_SERVICE}
      POSTGRES_USER: ${POSTGRES_USER_AUTH_SERVICE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_AUTH_SERVICE}
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER_AUTH_SERVICE} -d ${POSTGRES_DB_AUTH_SERVICE}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build: ../AuthService
    image: auth-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: ${DB_URL_AUTH_SERVICE}
      DB_USERNAME: ${DB_USERNAME_AUTH_SERVICE}
      DB_PASSWORD: ${DB_PASSWORD_AUTH_SERVICE}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres-auth-service

  postgres-order-service:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ${POSTGRES_DB_ORDER_SERVICE}
      POSTGRES_USER: ${POSTGRES_USER_ORDER_SERVICE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_ORDER_SERVICE}
    volumes:
      - postgres_order_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER_ORDER_SERVICE} -d ${POSTGRES_DB_ORDER_SERVICE}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  order-service:
    build: ../OrderService
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_URL: ${DB_URL_ORDER_SERVICE}
      DB_USERNAME: ${DB_USERNAME_ORDER_SERVICE}
      DB_PASSWORD: ${DB_PASSWORD_ORDER_SERVICE}
      JWT_SECRET: ${JWT_SECRET}
      EXTERNAL_USER_SERVICE_URL: ${EXTERNAL_USER_SERVICE_URL}
    depends_on:
      - postgres-order-service

  mongo:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo_payment_data:/data/db
      - ./mongo-init/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 10

  payment-service:
    build: ../PaymentService
    environment:
      MONGO_URL: ${MONGO_URL}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      EXTERNAL_PAYMENT_SERVICE_URL: ${EXTERNAL_PAYMENT_SERVICE_URL}
    depends_on:
      mongo:
        condition: service_healthy

  kafka:
    image: apache/kafka:3.9.2
    environment:
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka_payment_data:/apache/kafka
    healthcheck:
      test: [ "CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 15s

volumes:
  postgres_user_data:
  postgres_auth_data:
  postgres_order_data:
  mongo_payment_data:
  kafka_payment_data: